# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2316eae55cfa451aecc624712bfd92b81bc80180ed9866d52ab1c62027234b0ae3e82cb5fb729ddf96b6612bf94dae8fd1ad5f7c65c3bc1bea16243043b55ab

test:
  secret_key_base: e7d16cc6f48381c9ea98fce4cec01336e00c8f4e4fd6c3520ec3494f12319ffb6c7f76e0930a9ad95ba382928ee648550ea8deee7ce188be102c81a4778ab1a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
